name: GitHub Workflow matrix build

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        codev: [14, 15, 16]
    runs-on: ${{matrix.os}}
    steps:
      - name: Run build
        uses: actions/checkout@v5
        with:
          id: step1
          code-version: ${{matrix.codev}}
      - run: echo "Running on ${{matrix.os}} for version ${{matrix.codev}}"