name: GitHub Workflow matrix build

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        codev: [14, 15, 16]
      runs-on: ${{matrix.os}}
      steps:
        - id: step1
          with:
            code-version: ${{matrix.codev}}
        - run: echo "Running on ${{matrix.os}} for version ${{matrix.codev}}"